"""API Key management router.

Keys are generated by human users (owners/admins) and used by:
- Agents (autonomous AI agents interacting with the app)
- MCP servers (IDE integrations)
- CLI tools (hermes CLI)
- Skills (downloadable workflow packages)

All keys are scoped to a tenant and track session type for monitoring.
"""

import secrets
from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.database import get_db
from app.models import User, ApiKey, Tenant
from app.services.auth import (
    get_current_user,
    hash_api_key,
    create_access_token,
)

router = APIRouter(prefix="/api/keys", tags=["api-keys"])


# ─── Schemas ─────────────────────────────────────────────────────────────────

class CreateKeyRequest(BaseModel):
    name: str  # Human-readable label, e.g. "Production MCP Server"
    scope: str = "agent"  # agent, mcp, cli, skill
    permissions: str = "read"  # comma-separated: read, write, admin
    expires_in_days: int | None = None  # None = never expires


class CreateKeyResponse(BaseModel):
    id: int
    name: str
    scope: str
    permissions: str
    key_prefix: str
    full_key: str  # Only shown ONCE at creation time
    created_at: str
    expires_at: str | None


class KeyOut(BaseModel):
    id: int
    name: str
    scope: str
    permissions: str
    key_prefix: str
    is_active: bool
    created_at: str
    last_used_at: str | None
    expires_at: str | None
    created_by_email: str


class UpdateKeyRequest(BaseModel):
    name: str | None = None
    permissions: str | None = None
    is_active: bool | None = None


class AgentTokenRequest(BaseModel):
    """Request body for agent token exchange (API key → short-lived JWT)."""
    pass  # Key is in header, no body needed


class AgentTokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    tenant_slug: str
    session_type: str
    expires_in: int  # seconds


# ─── Key Generation ──────────────────────────────────────────────────────────

def _generate_api_key() -> str:
    """Generate a secure API key: riq_<40 random chars>."""
    return "riq_" + secrets.token_urlsafe(30)


# ─── CRUD Endpoints ──────────────────────────────────────────────────────────

@router.post("", response_model=CreateKeyResponse, status_code=201)
async def create_api_key(
    data: CreateKeyRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Generate a new API key. Only owners can create keys."""
    if not current_user.is_owner:
        raise HTTPException(status_code=403, detail="Only owners can create API keys")

    # Validate scope
    valid_scopes = {"agent", "mcp", "cli", "skill"}
    if data.scope not in valid_scopes:
        raise HTTPException(status_code=400, detail=f"Scope must be one of: {', '.join(valid_scopes)}")

    # Validate permissions
    valid_perms = {"read", "write", "admin"}
    perms = [p.strip() for p in data.permissions.split(",")]
    if not all(p in valid_perms for p in perms):
        raise HTTPException(status_code=400, detail=f"Permissions must be: {', '.join(valid_perms)}")

    # Generate key
    full_key = _generate_api_key()
    key_prefix = full_key[:8]
    key_hash = hash_api_key(full_key)

    expires_at = None
    if data.expires_in_days:
        expires_at = datetime.now(timezone.utc) + timedelta(days=data.expires_in_days)

    api_key = ApiKey(
        key_prefix=key_prefix,
        key_hash=key_hash,
        name=data.name,
        scope=data.scope,
        permissions=data.permissions,
        is_active=True,
        expires_at=expires_at,
        created_by_user_id=current_user.id,
        tenant_id=current_user.tenant_id,
    )
    db.add(api_key)
    await db.commit()
    await db.refresh(api_key)

    return CreateKeyResponse(
        id=api_key.id,
        name=api_key.name,
        scope=api_key.scope,
        permissions=api_key.permissions,
        key_prefix=key_prefix,
        full_key=full_key,  # Only shown once!
        created_at=api_key.created_at.isoformat(),
        expires_at=api_key.expires_at.isoformat() if api_key.expires_at else None,
    )


@router.get("", response_model=list[KeyOut])
async def list_api_keys(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List all API keys for the current tenant."""
    if not current_user.is_owner:
        raise HTTPException(status_code=403, detail="Only owners can view API keys")

    result = await db.execute(
        select(ApiKey)
        .where(ApiKey.tenant_id == current_user.tenant_id)
        .order_by(ApiKey.created_at.desc())
    )
    keys = result.scalars().all()

    return [
        KeyOut(
            id=k.id,
            name=k.name,
            scope=k.scope,
            permissions=k.permissions,
            key_prefix=k.key_prefix,
            is_active=k.is_active,
            created_at=k.created_at.isoformat(),
            last_used_at=k.last_used_at.isoformat() if k.last_used_at else None,
            expires_at=k.expires_at.isoformat() if k.expires_at else None,
            created_by_email=k.created_by.email if k.created_by else "unknown",
        )
        for k in keys
    ]


@router.get("/{key_id}", response_model=KeyOut)
async def get_api_key(
    key_id: int,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get details of a specific API key."""
    if not current_user.is_owner:
        raise HTTPException(status_code=403, detail="Only owners can view API keys")

    result = await db.execute(
        select(ApiKey).where(ApiKey.id == key_id, ApiKey.tenant_id == current_user.tenant_id)
    )
    key = result.scalar_one_or_none()
    if key is None:
        raise HTTPException(status_code=404, detail="API key not found")

    return KeyOut(
        id=key.id,
        name=key.name,
        scope=key.scope,
        permissions=key.permissions,
        key_prefix=key.key_prefix,
        is_active=key.is_active,
        created_at=key.created_at.isoformat(),
        last_used_at=key.last_used_at.isoformat() if key.last_used_at else None,
        expires_at=key.expires_at.isoformat() if key.expires_at else None,
        created_by_email=key.created_by.email if key.created_by else "unknown",
    )


@router.patch("/{key_id}", response_model=KeyOut)
async def update_api_key(
    key_id: int,
    data: UpdateKeyRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Update an API key (name, permissions, active status)."""
    if not current_user.is_owner:
        raise HTTPException(status_code=403, detail="Only owners can update API keys")

    result = await db.execute(
        select(ApiKey).where(ApiKey.id == key_id, ApiKey.tenant_id == current_user.tenant_id)
    )
    key = result.scalar_one_or_none()
    if key is None:
        raise HTTPException(status_code=404, detail="API key not found")

    if data.name is not None:
        key.name = data.name.strip()
    if data.permissions is not None:
        valid_perms = {"read", "write", "admin"}
        perms = [p.strip() for p in data.permissions.split(",")]
        if not all(p in valid_perms for p in perms):
            raise HTTPException(status_code=400, detail="Invalid permissions")
        key.permissions = data.permissions
    if data.is_active is not None:
        key.is_active = data.is_active

    await db.commit()
    await db.refresh(key)

    return KeyOut(
        id=key.id,
        name=key.name,
        scope=key.scope,
        permissions=key.permissions,
        key_prefix=key.key_prefix,
        is_active=key.is_active,
        created_at=key.created_at.isoformat(),
        last_used_at=key.last_used_at.isoformat() if key.last_used_at else None,
        expires_at=key.expires_at.isoformat() if key.expires_at else None,
        created_by_email=key.created_by.email if key.created_by else "unknown",
    )


@router.delete("/{key_id}")
async def revoke_api_key(
    key_id: int,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Revoke (deactivate) an API key. Cannot be undone."""
    if not current_user.is_owner:
        raise HTTPException(status_code=403, detail="Only owners can revoke API keys")

    result = await db.execute(
        select(ApiKey).where(ApiKey.id == key_id, ApiKey.tenant_id == current_user.tenant_id)
    )
    key = result.scalar_one_or_none()
    if key is None:
        raise HTTPException(status_code=404, detail="API key not found")

    key.is_active = False
    await db.commit()

    return {"status": "revoked", "key_id": key_id, "key_prefix": key.key_prefix}


# ─── Agent Token Exchange ────────────────────────────────────────────────────

@router.post("/exchange", response_model=AgentTokenResponse)
async def exchange_key_for_token(
    request: "Request",
    db: AsyncSession = Depends(get_db),
):
    """Exchange an API key for a short-lived JWT.

    Agents/MCP/CLI/Skills call this endpoint with their API key in the
    X-API-Key header to get a JWT they can use for subsequent API calls.
    This allows session tracking and monitoring.
    """
    from fastapi import Request as _Req
    from app.services.auth import authenticate_api_key

    user, session_info = await authenticate_api_key(request, db)

    # Mint a short-lived JWT with session metadata
    token = create_access_token(
        data={
            "user_id": user.id,
            "tenant_slug": session_info["tenant_slug"],
            "api_key_id": session_info["api_key_id"],
        },
        expires_delta=timedelta(minutes=30),
        session_type=session_info["session_type"],
    )

    return AgentTokenResponse(
        access_token=token,
        tenant_slug=session_info["tenant_slug"],
        session_type=session_info["session_type"],
        expires_in=1800,
    )


# Fix the type annotation for the exchange endpoint
from fastapi import Request  # noqa: E402
exchange_key_for_token.__annotations__["request"] = Request
